project:
  type: website
  output-dir: docs
  resources:
    - static/**

website:
  title: "Mayank Lal"
  search: false
  favicon: static/icons/site-icon.png
  site-url: "https://mayanklal.com"
  description: "Machine Learning | Risk Modeling | Finance | Storytelling"
  navbar:
    pinned: true
    headroom: false
    brand: "MAYANK LAL"
    right:
      - href: index.qmd
        text: "Root"
      - href: content/projects.qmd
        text: "Computes"
      - href: content/essays.qmd
        text: "Reveries"
      - href: content/diy.qmd
        text: "Assemblies"
      - href: content/viz.qmd
        text: "Pixels"
      - href: content/hobbies.qmd
        text: "π"

  page-footer:
    center: "Powered by Quarto · Mayank Lal © 2025"

format:
  html:
    css: /assets/css/styles_home.css
    include-in-header:
      - text: |
          <script src="/assets/js/tooltip.js"></script>
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">
    theme: flatly
    smooth-scroll: true
    toc: false
