project:
  type: website
  output-dir: docs

website:
  title: "Mayank Lal"
  favicon: static/icons/logo_favicon_512.png
  site-url: "https://mayanklal.com"
  description: "Data Scientist | Risk Modeling | Finance | Storytelling"
  navbar:
    left:
      - href: index.qmd
        text: "Root"
      - href: content/projects.qmd
        text: "Computes"
      - href: content/essays.qmd
        text: "Reveries"
      - href: content/diy.qmd
        text: "Assemblies"
      - href: content/viz.qmd
        text: "Pixels"
      - href: content/hobbies.qmd
        text: "Ï€"
       

format:
  html:
    css: assets/css/styles.css
    include-in-header:
      - text: |
          <script src="assets/js/tooltip.js"></script>
    theme: 
      light: flatly
      dark: darkly
    toggle:
      icon: moon-stars
      placement: right
      style: link
    smooth-scroll: true
    toc: false



